### ISSUE TITLE
Launch error on Paper-1.18.2-388

### ISSUE THREAD

**Issue by JKearnsl** [jpenilla/squaremap#140]
**Paper version:** [Paper-1.18.2-388](https://api.papermc.io/v2/projects/paper/versions/1.18.2/builds/388/downloads/paper-1.18.2-388.jar)
**Squaremap version:** [squaremap-paper-mc1.20.2-1.2.1.jar](https://github.com/jpenilla/squaremap/releases/download/v1.2.1/squaremap-paper-mc1.20.2-1.2.1.jar)

**Error when starting the server:**
```bash
[15:43:53] [Server thread/ERROR]: Could not load 'plugins/squaremap-paper-mc1.20.2-1.2.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.20
	at org.bukkit.craftbukkit.v1_18_R2.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:375) ~[paper-1.18.2.jar:git-Paper-388]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:415) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:323) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:418) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

<details>

  <summary>Full Launch logs</summary>

```bash
[15:43:50] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[15:43:51] [Worker-Main-2/INFO]: Loaded 7 recipes
[15:43:52] [Server thread/INFO]: Starting minecraft server version 1.18.2
[15:43:52] [Server thread/INFO]: Loading properties
[15:43:52] [Server thread/INFO]: This server is running Paper version git-Paper-388 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc9ee65 on ver/1.18.2)
[15:43:52] [Server thread/INFO]: Server Ping Player Sample Count: 12
[15:43:52] [Server thread/INFO]: Using 4 threads for Netty based IO
[15:43:52] [Server thread/INFO]: Default game type: SURVIVAL
[15:43:52] [Server thread/INFO]: Generating keypair
[15:43:52] [Server thread/INFO]: Starting Minecraft server on *:25565
[15:43:52] [Server thread/INFO]: Using epoll channel type
[15:43:52] [Server thread/INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[15:43:52] [Server thread/INFO]: Paper: Using Java cipher from Velocity.
[15:43:53] [Server thread/ERROR]: Could not load 'plugins/squaremap-paper-mc1.20.2-1.2.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.20
	at org.bukkit.craftbukkit.v1_18_R2.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:375) ~[paper-1.18.2.jar:git-Paper-388]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:415) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:323) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:418) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[15:43:54] [Server thread/INFO]: [TerraformGenerator] Loading TerraformGenerator v11.1.1
[15:43:54] [Server thread/INFO]: [ViaVersion] Loading ViaVersion v4.8.1
[15:43:54] [Server thread/INFO]: [ViaVersion] ViaVersion 4.8.1 is now loaded. Registering protocol transformers and injecting...
[15:43:54] [Via-Mappingloader-0/INFO]: [ViaVersion] Loading block connection mappings ...
[15:43:54] [Server thread/INFO]: [Chunky] Loading Chunky v1.3.92
[15:43:54] [Server thread/INFO]: [TabTPS] Loading TabTPS v1.3.21
[15:43:54] [Server thread/INFO]: [floodgate] Loading floodgate v2.2.2-SNAPSHOT (b85-71acc6c)
[15:43:54] [Via-Mappingloader-0/INFO]: [ViaVersion] Using FastUtil Long2ObjectOpenHashMap for block connections
[15:43:55] [Server thread/INFO]: [floodgate] На запуск Floodgate потребовалось 510мс
[15:43:55] [Server thread/INFO]: [MiniMOTD] Loading MiniMOTD v2.0.14
[15:43:55] [Server thread/INFO]: [Geyser-Spigot] Loading Geyser-Spigot v2.2.0-SNAPSHOT
[15:43:55] [Server thread/INFO]: [Geyser-Spigot] Загрузка расширений...
[15:43:55] [Server thread/INFO]: [Geyser-Spigot] Загружено расширений: 0
[15:43:55] [Server thread/INFO]: [ChunkyBorder] Loading ChunkyBorder v1.1.50
[15:43:55] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[15:43:55] [Server thread/INFO]: [TerraformGenerator] Enabling TerraformGenerator v11.1.1
[15:43:55] [Server thread/INFO]: [TerraformGenerator] Custom Logger Initialized
[15:43:55] [Server thread/INFO]: [TerraformGenerator] bStats Metrics enabled.
[15:43:55] [Server thread/INFO]: [TerraformGenerator] Detected version: v1_18_R2, number: 18.2
[15:43:55] [Server thread/INFO]: Preparing level "world"
[15:43:56] [Server thread/INFO]: [TerraformGenerator] Detected world: world, commencing injection... 
[15:43:56] [Server thread/INFO]: [TerraformGenerator] Injection success! Proceeding with generation.
[15:43:56] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[15:43:56] [Server thread/INFO]: Time elapsed: 264 ms
[15:43:56] [Server thread/INFO]: [TerraformGenerator] world loaded.
[15:43:56] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[15:43:56] [Server thread/INFO]: Time elapsed: 139 ms
[15:43:56] [Server thread/INFO]: [ViaVersion] Enabling ViaVersion v4.8.1
[15:43:57] [Server thread/INFO]: [ViaVersion] ViaVersion detected server version: 1.18.2 (758)
[15:43:57] [Server thread/INFO]: [Chunky] Enabling Chunky v1.3.92
[15:43:57] [Server thread/INFO]: [TabTPS] Enabling TabTPS v1.3.21
[15:43:57] [Server thread/INFO]: [TabTPS] Successfully registered Mojang Brigadier support for commands.
[15:43:57] [Server thread/INFO]: [TabTPS] Successfully registered asynchronous command completion listener.
[15:43:58] [Server thread/INFO]: [floodgate] Enabling floodgate v2.2.2-SNAPSHOT (b85-71acc6c)
[15:43:58] [Server thread/INFO]: [MiniMOTD] Enabling MiniMOTD v2.0.14
[15:43:58] [Server thread/INFO]: [Geyser-Spigot] Enabling Geyser-Spigot v2.2.0-SNAPSHOT
[15:43:58] [Server thread/INFO]: [ChunkyBorder] Enabling ChunkyBorder v1.1.50
[15:43:58] [Server thread/INFO]: [Geyser-Spigot] ******************************************
[15:43:58] [Server thread/INFO]: [Geyser-Spigot] 
[15:43:58] [Server thread/INFO]: [Geyser-Spigot] Загрузка Geyser версии 2.2.0-SNAPSHOT (git-master-13339f1)
[15:43:58] [Server thread/INFO]: [Geyser-Spigot] 
[15:43:58] [Server thread/INFO]: [Geyser-Spigot] ******************************************
[15:44:02] [Server thread/INFO]: [Geyser-Spigot] Geyser запущен на 0.0.0.0:19132
[15:44:02] [Server thread/INFO]: [Geyser-Spigot] Выполнено (4,084сек.)! Используйте команду /geyser help для помощи!
[15:44:02] [Server thread/INFO]: Running delayed init tasks
[15:44:02] [Craft Scheduler Thread - 2 - ViaVersion/INFO]: [ViaVersion] Finished mapping loading, shutting down loader executor!
[15:44:02] [Server thread/INFO]: Done (10.265s)! For help, type "help"
[15:44:02] [Server thread/INFO]: Timings Reset
[15:48:23] [Server thread/INFO]: [STDOUT] [org.spigotmc.RestartCommand] Attempting to restart with ./start.sh
[15:48:23] [Server thread/INFO]: Stopping server
[15:48:23] [Server thread/INFO]: [ChunkyBorder] Disabling ChunkyBorder v1.1.50
[15:48:23] [Server thread/INFO]: [Geyser-Spigot] Disabling Geyser-Spigot v2.2.0-SNAPSHOT
[15:48:23] [Server thread/INFO]: [Geyser-Spigot] Выключение Geyser.
[15:48:23] [Server thread/INFO]: [Geyser-Spigot] Geyser успешно выключен.
[15:48:23] [Server thread/INFO]: [MiniMOTD] Disabling MiniMOTD v2.0.14
[15:48:23] [Server thread/INFO]: [floodgate] Disabling floodgate v2.2.2-SNAPSHOT (b85-71acc6c)
[15:48:23] [Server thread/INFO]: [TabTPS] Disabling TabTPS v1.3.21
[15:48:23] [Server thread/INFO]: [Chunky] Disabling Chunky v1.3.92
[15:48:23] [Server thread/INFO]: [ViaVersion] Disabling ViaVersion v4.8.1
[15:48:23] [Server thread/INFO]: [ViaVersion] ViaVersion is disabling, if this is a reload and you experience issues consider rebooting.
[15:48:23] [Server thread/INFO]: [TerraformGenerator] Disabling TerraformGenerator v11.1.1
[15:48:23] [Server thread/INFO]: Saving players
[15:48:23] [WebSocketConnectReadThread-84/INFO]: [Geyser-Spigot] The skin uploader has been closed
[15:48:23] [Server thread/INFO]: Saving worlds
[15:48:23] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[15:48:24] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[15:48:24] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[15:48:24] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[15:48:24] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[15:48:24] [Server thread/INFO]: Flushing Chunk IO
[15:48:24] [Server thread/INFO]: Closing Thread Pool
[15:48:24] [Server thread/INFO]: Closing Server
```  

</details>  

**Plugins**
- Chunky-1.3.92
- ChunkyBorder-1.1.50
- floodgate-spigot
- Geyser-Spigot
- minimotd-bukkit-2.0.14
- squaremap-paper-mc1.20.2-1.2.1
- tabtps-spigot-1.3.21
- TerraformGenerator-11.1.1_1.16.5-1.20.2
- ViaVersion-4.8.1

**Comment by jpenilla** [comment]
As the file name says, that version of squaremap is for 1.20.2. You will need to download an old and unsupported build for 1.18.2.
