### ISSUE TITLE
folia error

### ISSUE THREAD

**Issue by xiaoluofa** [jpenilla/squaremap#193]
[15:33:21 WARN]: [squaremap] Global task for squaremap v1.2.4-SNAPSHOT+976798d generated an exception
java.lang.NoClassDefFoundError: Could not initialize class xyz.jpenilla.squaremap.api.ProviderHolder
        at xyz.jpenilla.squaremap.api.HtmlComponentSerializer.withFlattener(HtmlComponentSerializer.java:28) ~[squaremap-paper-mc1.20.4-1.2.4-SNAPSHOT+976798d.jar:?]
        at xyz.jpenilla.squaremap.common.task.UpdatePlayers.run(UpdatePlayers.java:57) ~[squaremap-paper-mc1.20.4-1.2.4-SNAPSHOT+976798d.jar:?]
        at xyz.jpenilla.squaremap.paper.SquaremapPaper.lambda$startCallback$0(SquaremapPaper.java:97) ~[squaremap-paper-mc1.20.4-1.2.4-SNAPSHOT+976798d.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[luminol-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[luminol-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalStateException: Encountered an exception loading service interface xyz.jpenilla.squaremap.api.HtmlStripper$Provider [in thread "Region Scheduler Thread #1"]
        at net.kyori.adventure.util.Services.service(Services.java:60) ~[adventure-api-4.15.0.jar:?]
        at xyz.jpenilla.squaremap.api.ProviderHolder.service(ProviderHolder.java:10) ~[squaremap-paper-mc1.20.4-1.2.4-SNAPSHOT+976798d.jar:?]
        at xyz.jpenilla.squaremap.api.ProviderHolder.<clinit>(ProviderHolder.java:7) ~[squaremap-paper-mc1.20.4-1.2.4-SNAPSHOT+976798d.jar:?]
        ... 10 more

**Comment by jpenilla** [comment]
I am unable to reproduce this on Folia 1.20.4. I also don't have time to support forks of Folia, if something works on Folia but not a fork, there is nothing to fix on the squaremap end.
