### ISSUE TITLE
In fact, using folia can also trigger an error.

### ISSUE THREAD

**Issue by xiaoluofa** [jpenilla/squaremap#195]
[23:56:51 WARN]: [squaremap] Global task for squaremap v1.2.4-SNAPSHOT+976798d generated an exception
java.lang.NoClassDefFoundError: Could not initialize class xyz.jpenilla.squaremap.api.ProviderHolder
        at xyz.jpenilla.squaremap.api.HtmlComponentSerializer.withFlattener(HtmlComponentSerializer.java:28) ~[squaremap-paper-mc1.20.4-1.2.4-SNAPSHOT+976798d.jar:?]
        at xyz.jpenilla.squaremap.common.task.UpdatePlayers.run(UpdatePlayers.java:57) ~[squaremap-paper-mc1.20.4-1.2.4-SNAPSHOT+976798d.jar:?]
        at xyz.jpenilla.squaremap.paper.SquaremapPaper.lambda$startCallback$0(SquaremapPaper.java:97) ~[squaremap-paper-mc1.20.4-1.2.4-SNAPSHOT+976798d.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[folia-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[folia-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalStateException: Encountered an exception loading service interface xyz.jpenilla.squaremap.api.HtmlStripper$Provider [in thread "Region Scheduler Thread #0"]
        at net.kyori.adventure.util.Services.service(Services.java:60) ~[adventure-api-4.15.0.jar:?]
        at xyz.jpenilla.squaremap.api.ProviderHolder.service(ProviderHolder.java:10) ~[squaremap-paper-mc1.20.4-1.2.4-SNAPSHOT+976798d.jar:?]
        at xyz.jpenilla.squaremap.api.ProviderHolder.<clinit>(ProviderHolder.java:7) ~[squaremap-paper-mc1.20.4-1.2.4-SNAPSHOT+976798d.jar:?]
        ... 10 more

**Comment by jpenilla** [comment]
For future reference, it's always useful to include a full log, what you shared cuts out the useful part...

https://mclo.gs can remove sensitive info automatically.
