### ISSUE TITLE
squaremap 1.2.4 fabric (minecraft 1.20.4) crashes when the server is loading

### ISSUE THREAD

**Issue by nanopone** [jpenilla/squaremap#226]
```
[15:40:29] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'squaremap'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.11.jar:?]
        at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric.jar:1.0.1]
Caused by: java.lang.NoClassDefFoundError: cloud/commandframework/brigadier/BrigadierManagerHolder
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:3373) ~[?:?]
        at java.lang.Class.getDeclaredConstructors(Class.java:2555) ~[?:?]
        at squaremap.libraries.com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:299) ~[squaremap-fabric-mc1.20.4-1.2.3.jar:?]
        at squaremap.libraries.com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:121) ~[squaremap-fabric-mc1.20.4-1.2.3.jar:?]
        at squaremap.libraries.com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:715) ~[squaremap-fabric-mc1.20.4-1.2.3.jar:?]
        at squaremap.libraries.com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:941) ~[squaremap-fabric-mc1.20.4-1.2.3.jar:?]
        at squaremap.libraries.com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:863) ~[squaremap-fabric-mc1.20.4-1.2.3.jar:?]
        at squaremap.libraries.com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:300) ~[squaremap-fabric-mc1.20.4-1.2.3.jar:?]
        at squaremap.libraries.com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:223) ~[squaremap-fabric-mc1.20.4-1.2.3.jar:?]
        at squaremap.libraries.com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:949) ~[squaremap-fabric-mc1.20.4-1.2.3.jar:?]
        at squaremap.libraries.com.google.inject.internal.FactoryProxy.notify(FactoryProxy.java:48) ~[squaremap-fabric-mc1.20.4-1.2.3.jar:?]
        at squaremap.libraries.com.google.inject.internal.ProcessedBindingData.runCreationListeners(ProcessedBindingData.java:60) ~[squaremap-fabric-mc1.20.4-1.2.3.jar:?]
        at squaremap.libraries.com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:137) ~[squaremap-fabric-mc1.20.4-1.2.3.jar:?]
        at squaremap.libraries.com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110) ~[squaremap-fabric-mc1.20.4-1.2.3.jar:?]
        at squaremap.libraries.com.google.inject.Guice.createInjector(Guice.java:87) ~[squaremap-fabric-mc1.20.4-1.2.3.jar:?]
        at squaremap.libraries.com.google.inject.Guice.createInjector(Guice.java:69) ~[squaremap-fabric-mc1.20.4-1.2.3.jar:?]
        at xyz.jpenilla.squaremap.fabric.SquaremapFabric.<init>(SquaremapFabric.java:46) ~[squaremap-fabric-mc1.20.4-1.2.3.jar:?]
        at xyz.jpenilla.squaremap.fabric.SquaremapFabric$Initializer.onInitialize(SquaremapFabric.java:162) ~[squaremap-fabric-mc1.20.4-1.2.3.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: cloud.commandframework.brigadier.BrigadierManagerHolder
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:3373) ~[?:?]
        at java.lang.Class.getDeclaredConstructors(Class.java:2555) ~[?:?]
        at squaremap.libraries.com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:299) ~[squaremap-fabric-mc1.20.4-1.2.3.jar:?]
        at squaremap.libraries.com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:121) ~[squaremap-fabric-mc1.20.4-1.2.3.jar:?]
        at squaremap.libraries.com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:715) ~[squaremap-fabric-mc1.20.4-1.2.3.jar:?]
        at squaremap.libraries.com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:941) ~[squaremap-fabric-mc1.20.4-1.2.3.jar:?]
        at squaremap.libraries.com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:863) ~[squaremap-fabric-mc1.20.4-1.2.3.jar:?]
        at squaremap.libraries.com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:300) ~[squaremap-fabric-mc1.20.4-1.2.3.jar:?]
        at squaremap.libraries.com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:223) ~[squaremap-fabric-mc1.20.4-1.2.3.jar:?]
        at squaremap.libraries.com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:949) ~[squaremap-fabric-mc1.20.4-1.2.3.jar:?]
        at squaremap.libraries.com.google.inject.internal.FactoryProxy.notify(FactoryProxy.java:48) ~[squaremap-fabric-mc1.20.4-1.2.3.jar:?]
        at squaremap.libraries.com.google.inject.internal.ProcessedBindingData.runCreationListeners(ProcessedBindingData.java:60) ~[squaremap-fabric-mc1.20.4-1.2.3.jar:?]
        at squaremap.libraries.com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:137) ~[squaremap-fabric-mc1.20.4-1.2.3.jar:?]
        at squaremap.libraries.com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110) ~[squaremap-fabric-mc1.20.4-1.2.3.jar:?]
        at squaremap.libraries.com.google.inject.Guice.createInjector(Guice.java:87) ~[squaremap-fabric-mc1.20.4-1.2.3.jar:?]
        at squaremap.libraries.com.google.inject.Guice.createInjector(Guice.java:69) ~[squaremap-fabric-mc1.20.4-1.2.3.jar:?]
        at xyz.jpenilla.squaremap.fabric.SquaremapFabric.<init>(SquaremapFabric.java:46) ~[squaremap-fabric-mc1.20.4-1.2.3.jar:?]
        at xyz.jpenilla.squaremap.fabric.SquaremapFabric$Initializer.onInitialize(SquaremapFabric.java:162) ~[squaremap-fabric-mc1.20.4-1.2.3.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
        ... 7 more
```

**Comment by jpenilla** [comment]
Some other mod is loading cloud v2 while squaremap 1.2.4 uses cloud v1 still. You can use [this build](https://jenkins.jpenilla.xyz/job/squaremap/376/) to resolve it, will also be fixed in the upcoming 1.2.5 release for 1.20.6.
