### ISSUE TITLE
Error showed up on console it said to report it

### ISSUE THREAD

**Issue by TweekerX** [jpenilla/squaremap#257]
23:08:07 WARN]: [SuperVanish] Unknown exception occurred!
[23:08:07 WARN]: [SuperVanish] Please report this issue!
[23:08:07 WARN]: [SuperVanish] Message: 
[23:08:07 WARN]: [SuperVanish]   Field index 0 is out of bounds for length 0
[23:08:07 WARN]: [SuperVanish] General information: 
[23:08:07 WARN]: [SuperVanish]   ServerVersion: 1.21-109-5a5035b (MC: 1.21)
[23:08:07 WARN]: [SuperVanish]   PluginVersion: 6.2.19
[23:08:07 WARN]: [SuperVanish]   ServerPlugins: ProtocolLib v5.3.0-SNAPSHOT-726, squaremap v1.2.6, floodgate v2.2.3-SNAPSHOT (b109-49bd564), LuckPerms v5.4.134, Chunky v1.4.10, Geyser-Spigot v2.4.0-SNAPSHOT, CoreProtect v22.4, FreedomChat v1.7.0, InventoryRollbackPlus v1.6.17, DiscordSRV v1.27.0,
[23:08:07 WARN]: [SuperVanish] Settings:
[23:08:07 WARN]: [SuperVanish]   MsgsVersion: 6.2.17
[23:08:07 WARN]: [SuperVanish]   Settings: ||InvisibilityFeatures.NightVisionEffect>true||InvisibilityFeatures.DisableDamage>true||InvisibilityFeatures.DisableHunger>true||InvisibilityFeatures.DisableMobTarget>true||InvisibilityFeatures.OpenChestsSilently>true||InvisibilityFeatures.DisablePressurePlates>true||InvisibilityFeatures.DisablePush>false||InvisibilityFeatures.DefaultPickUpItemsOption>false||InvisibilityFeatures.ModifyTablistPackets>true||InvisibilityFeatures.ModifyTabCompletePackets>true||InvisibilityFeatures.PreventSculkSensorActivation>true||InvisibilityFeatures.PreventTurtleEggBreaking>true||InvisibilityFeatures.DisableDripLeaf>true||InvisibilityFeatures.PreventRaidTriggering>true||InvisibilityFeatures.Fly.Enable>false||InvisibilityFeatures.Fly.DisableOnReappear>true||VanishStateFeatures.AutoVanishOnJoin>false||VanishStateFeatures.ReappearOnWorldChange>false||VanishStateFeatures.ReappearOnQuit>false||VanishStateFeatures.CheckPermissionOnWorldChange>false||VanishStateFeatures.CheckPermissionOnQuit>false||VanishStateFeatures.CheckPermissionOnLogin>false||IndicationFeatures.LayeredPermissions.EnableSeePermission>true||IndicationFeatures.LayeredPermissions.LayeredSeeAndUsePermissions>false||IndicationFeatures.LayeredPermissions.MaxLevel>100||IndicationFeatures.MarkVanishedPlayersAsSpectators>true||MessageOptions.FakeJoinQuitMessages.BroadcastFakeQuitOnVanish>true||MessageOptions.FakeJoinQuitMessages.BroadcastFakeJoinOnReappear>true||MessageOptions.FakeJoinQuitMessages.AnnounceVanishReappearToAdmins>true||MessageOptions.FakeJoinQuitMessages.SendMessageOnlyToAdmins>false||MessageOptions.FakeJoinQuitMessages.SendMessageOnlyToUsers>false||MessageOptions.HideRealJoinQuitMessages>true||MessageOptions.ReappearOnQuitHideLeaveMsg>true||MessageOptions.AnnounceRealJoinQuitToAdmins>true||MessageOptions.AnnounceDeathToAdmins>true||MessageOptions.RemindVanishedOnJoin>true||MessageOptions.DisplayActionBar>true||RestrictiveOptions.PreventBlockBreaking>false||RestrictiveOptions.PreventBlockPlacing>false||RestrictiveOptions.PreventHittingEntities>false||ExternalInvisibility.ServerList.AdjustAmountOfOnlinePlayers>true||ExternalInvisibility.ServerList.AdjustListOfLoggedInPlayers>true||HookOptions.EnableEssentialsHook>true||HookOptions.EnableDynmapHook>true||HookOptions.DynmapSendJoinLeaveMessages>true||HookOptions.EnableTrailGUIHook>true||HookOptions.EnablePlaceholderAPIHook>true||HookOptions.EnableMVdWPlaceholderAPIHook>true||HookOptions.EnableCitizensHook>true||CompatibilityOptions.PlayerJoinEventPriority>HIGH||CompatibilityOptions.PlayerQuitEventPriority>HIGH||MiscellaneousOptions.UpdateChecker.Enable>true||MiscellaneousOptions.UpdateChecker.NotifyAdmins>true||ConfigVersion>6.2.17||
[23:08:07 WARN]: [SuperVanish] StackTrace: 
[23:08:07 WARN]: FieldAccessException: Field index 0 is out of bounds for length 0
[23:08:07 WARN]:        at ProtocolLib (3).jar//com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49)
[23:08:07 WARN]:        at ProtocolLib (3).jar//com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:247)
[23:08:07 WARN]:        at SuperVanish.jar//de.myzelyam.supervanish.visibility.hiders.modules.TabCompleteModule.onPacketSending(TabCompleteModule.java:47)
[23:08:07 WARN]:        at ProtocolLib (3).jar//com.comphenix.protocol.injector.collection.OutboundPacketListenerSet.invokeListener(OutboundPacketListenerSet.java:74)
[23:08:07 WARN]:        at ProtocolLib (3).jar//com.comphenix.protocol.injector.collection.PacketListenerSet.lambda$invoke$0(PacketListenerSet.java:120)
[23:08:07 WARN]:        at ProtocolLib (3).jar//com.comphenix.protocol.timing.TimingTracker.lambda$static$0(TimingTracker.java:7)
[23:08:07 WARN]:        at ProtocolLib (3).jar//com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:120)
[23:08:07 WARN]:        at ProtocolLib (3).jar//com.comphenix.protocol.injector.collection.OutboundPacketListenerSet.invoke(OutboundPacketListenerSet.java:30)
[23:08:07 WARN]:        at ProtocolLib (3).jar//com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:99)
[23:08:07 WARN]:        at ProtocolLib (3).jar//com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:528)
[23:08:07 WARN]:        at ProtocolLib (3).jar//com.comphenix.protocol.injector.PacketFilterManager.invokeOutboundPacketListeners(PacketFilterManager.java:516)
[23:08:07 WARN]:        at ProtocolLib (3).jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:528)
[23:08:07 WARN]:        at ProtocolLib (3).jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:44)
[23:08:07 WARN]:        at ProtocolLib (3).jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:233)
[23:08:07 WARN]:        at net.minecraft.network.Connection.sendPacket(Connection.java:497)
[23:08:07 WARN]:        at net.minecraft.network.Connection.send(Connection.java:457)
[23:08:07 WARN]:        at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:312)
[23:08:07 WARN]:        at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:293)
[23:08:07 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$sendServerSuggestions$5(ServerGamePacketListenerImpl.java:846)
[23:08:07 WARN]:        at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757)
[23:08:07 WARN]:        at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735)
[23:08:07 WARN]:        at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2214)
[23:08:07 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.sendServerSuggestions(ServerGamePacketListenerImpl.java:836)
[23:08:07 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleCustomCommandSuggestions0$2(ServerGamePacketListenerImpl.java:797)
[23:08:07 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[23:08:07 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[23:08:07 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[23:08:07 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1536)
[23:08:07 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[23:08:07 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[23:08:07 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1513)
[23:08:07 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1506)
[23:08:07 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[23:08:07 WARN]:        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1465)
[23:08:07 WARN]:        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1472)
[23:08:07 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1317)
[23:08:07 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[23:08:07 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[23:08:07 WARN]: [SuperVanish] Please include this information
[23:08:07 WARN]: [SuperVanish] if you report the issue.

**Comment by jpenilla** [comment]
There is no squaremap error in this log

**Comment by TweekerX** [comment]
sorry clicked the wrong plugin
