### ISSUE TITLE
Chunks no longer render Properly, and if i do a fullrender the console is spammed with this, which also comes up occasionally

### ISSUE THREAD

**Issue by Bandanakeks** [jpenilla/squaremap#260]
Purpur 1.21, other plugins are FAWE,Chunky,Coreprotect,Geyser&Floodgate, Map still loads, but does not seem to update correctly leaving big holes.

Error Message: 
13:32:48 WARN]: [squaremap] Exception mapping chunk column starting at [-643, -768] in minecraft:the_end
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: ca/spottedleaf/moonrise/common/util/ChunkSystem
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1576) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1553) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1546) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1505) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1627) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1337) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[purpur-1.21.jar:1.21-2257-cb0f04b]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: ca/spottedleaf/moonrise/common/util/ChunkSystem
        at squaremap-paper-mc1.21-1.2.6 (1).jar/xyz.jpenilla.squaremap.paper.util.chunksnapshot.PaperChunkSnapshotProvider.lambda$asyncSnapshot$0(PaperChunkSnapshotProvider.java:37) ~[squaremap-paper-mc1.21-1.2.6 (1).jar:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 14 more

**Comment by Bandanakeks** [comment]
Also it seems it is unable to generate the map based on world data, and ´can only update (badly and with holes) when a player loaded the chunks

**Comment by jpenilla** [comment]
squaremap 1.2.6 needs the latest Paper 1.21 build, 1.2.5 is needed for earlier builds but really you should just update your server. Purpur is not something squaremap explicitly supports but I would guess they have updated builds including the latest Paper changes as well.
