### ISSUE TITLE
[Sponge] StackOverflowError on startup

### ISSUE THREAD

**Issue by SamB440** [jpenilla/squaremap#297]
```
[17Sep2024 16:24:55] [Server thread/ERROR] [sponge]: Could not pass StartedEngineEvent$Impl to squaremap
java.lang.StackOverflowError: null
	at squaremap.libraries.org.incendo.cloud.sponge.SpongeRegistrationHandler.unwrap(SpongeRegistrationHandler.java:136) ~[SpongeRegistrationHandler.class:?]
	at squaremap.libraries.org.incendo.cloud.sponge.SpongeRegistrationHandler.unwrap(SpongeRegistrationHandler.java:136) ~[SpongeRegistrationHandler.class:?]
	at squaremap.libraries.org.incendo.cloud.sponge.SpongeRegistrationHandler.unwrap(SpongeRegistrationHandler.java:136) ~[SpongeRegistrationHandler.class:?]
	at squaremap.libraries.org.incendo.cloud.sponge.SpongeRegistrationHandler.unwrap(SpongeRegistrationHandler.java:136) ~[SpongeRegistrationHandler.class:?]
	at squaremap.libraries.org.incendo.cloud.sponge.SpongeRegistrationHandler.unwrap(SpongeRegistrationHandler.java:136) ~[SpongeRegistrationHandler.class:?]
	at squaremap.libraries.org.incendo.cloud.sponge.SpongeRegistrationHandler.unwrap(SpongeRegistrationHandler.java:136) ~[SpongeRegistrationHandler.class:?]
(and so on)
```

Version:
```
[16:28:46] [Server thread/INFO]: SpongeVanilla
    Minecraft: 1.21.1
    SpongeAPI: 12.0.0-SNAPSHOT
    Sponge: 1.21.1-12.0.0-SNAPSHOT
    SpongeVanilla: 1.21.1-12.0.0-RC0
    JVM: 22.0.2/64-bit (Eclipse Adoptium)
    OS: Linux/6.1.0-25-amd64 (amd64)
```

Squaremap 1.2.7.

**Comment by jpenilla** [comment]
Will be fixed in the next dev build
https://github.com/Incendo/cloud-minecraft-modded/commit/d19fd342b1b959d7bc9175341c65152b863d156b
