### ISSUE TITLE
squaremap-worldguard exception with latest plugin version

### ISSUE THREAD

**Issue by RehabCZ** [jpenilla/squaremap#32]
Hi,
Just updated to the latest version of SQMap and get exception with worldguard addon.

_Using versions:_
**WorldGuard**: `worldguard-bukkit-7.0.7-SNAPSHOT`
**SquareMap**: `squaremap-paper-mc1.18.1-1.1.1`

_LOG_:
```
[squaremap-worldguard] Plugin squaremap-worldguard v1.0.0-SNAPSHOT generated an exception while executing task 80
java.lang.NoSuchMethodError: 'java.lang.String xyz.jpenilla.squaremap.api.MapWorld.name()'
        at xyz.jpenilla.squaremap.addon.worldguard.task.SquaremapTask.handleClaim(SquaremapTask.java:83) ~[squaremap-worldguard-1.0.0-SNAPSHOT.jar:?]
        at xyz.jpenilla.squaremap.addon.worldguard.task.SquaremapTask.lambda$updateClaims$0(SquaremapTask.java:49) ~[squaremap-worldguard-1.0.0-SNAPSHOT.jar:?]
        at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
        at java.util.Collections$UnmodifiableMap.forEach(Collections.java:1553) ~[?:?]
        at xyz.jpenilla.squaremap.addon.worldguard.task.SquaremapTask.updateClaims(SquaremapTask.java:49) ~[squaremap-worldguard-1.0.0-SNAPSHOT.jar:?]
        at xyz.jpenilla.squaremap.addon.worldguard.task.SquaremapTask.run(SquaremapTask.java:40) ~[squaremap-worldguard-1.0.0-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-207]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.1.jar:git-Paper-207]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.1.jar:git-Paper-207]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by jpenilla** [comment]
Wrong repo, but your squaremap-worldguard is outdated.
