### ISSUE TITLE
Crash on render

### ISSUE THREAD

**Issue by Lord-Vlad** [jpenilla/squaremap#33]
```
---- Minecraft Crash Report ----
// Don't do that.

Description: Exception in server tick loop

java.util.concurrent.CompletionException: net.minecraft.class_148: Loading NBT data
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:636)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at com.mojang.datafixers.util.Either$Right.ifRight(Either.java:109)
	at net.minecraft.class_3906.method_27917(class_3906.java:29)
	at net.minecraft.class_3906$1.method_16901(class_3906.java:44)
	at net.minecraft.class_4698.method_27939(class_4698.java:150)
	at net.minecraft.class_3847$class_3907.run(class_3847.java:59)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: net.minecraft.class_148: Loading NBT data
	at net.minecraft.class_2507.method_10626(class_2507.java:136)
	at net.minecraft.class_2507.method_10625(class_2507.java:75)
	at net.minecraft.class_2507.method_10627(class_2507.java:71)
	at net.minecraft.class_2867.method_17911(class_2867.java:57)
	at net.minecraft.class_4698.method_27943(class_4698.java:100)
	... 8 more
Caused by: java.io.EOFException
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:273)
	at net.minecraft.class_2487.method_10542(class_2487.java:480)
	at net.minecraft.class_2487$1.method_23240(class_2487.java:67)
	at net.minecraft.class_2487$1.method_23262(class_2487.java:57)
	at net.minecraft.class_2507.method_10626(class_2507.java:131)
	... 12 more
```

**Comment by Lord-Vlad** [comment]
Has nothing to do with squaremap.
