### ISSUE TITLE
Input does not contain a key [element_type]: MapLike[{}] // Exception loading structure piece with id minecraft:jigsaw

### ISSUE THREAD

**Issue by jdstankosky** [jpenilla/squaremap#41]
I recently did a fullrender on my server (the map on everyone's browser had stopped updating displayed data and I did this in an attempt to fix it)  and this same error kept popping up very frequently in console:

```
[03:39:27] [Server thread/ERROR]: Input does not contain a key [element_type]: MapLike[{}]
[03:39:27] [Server thread/ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid pool element found
        at net.minecraft.class_3790.method_35448(class_3790.java:54) ~[server-intermediary.jar:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.minecraft.class_3790.<init>(class_3790.java:54) ~[server-intermediary.jar:?]
        at net.minecraft.class_6624.method_38711(class_6624.java:73) ~[server-intermediary.jar:?]
        at net.minecraft.class_3195.method_28660(class_3195.java:129) ~[server-intermediary.jar:?]
        at net.minecraft.class_2852.method_12392(class_2852.java:468) ~[server-intermediary.jar:?]
        at net.minecraft.class_2852.method_12395(class_2852.java:199) ~[server-intermediary.jar:?]
        at net.minecraft.class_3898.method_17256(class_3898.java:605) ~[server-intermediary.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
        at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:552) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
        at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:561) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[server-intermediary.jar:?]
        at net.minecraft.class_3215.method_17299(class_3215.java:197) ~[server-intermediary.jar:?]
        at xyz.jpenilla.squaremap.common.util.VanillaChunkSnapshotProvider.fullChunkIfGenerated(VanillaChunkSnapshotProvider.java:66) ~[squaremap-fabric-mc1.18.2-1.1.2.jar:?]
        at xyz.jpenilla.squaremap.common.util.VanillaChunkSnapshotProvider.lambda$asyncSnapshot$0(VanillaChunkSnapshotProvider.java:32) ~[squaremap-fabric-mc1.18.2-1.1.2.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:808) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:790) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:784) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:768) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

The map rendering finally finished with 739328 chunks in 00:49:40. No other errors noticed.

**Comment by jpenilla** [comment]
Vanilla issue when loading/upgrading old chunks https://bugs.mojang.com/browse/MC-227945
