### ISSUE TITLE
Problem with Squaremap wanting to change settings.json

### ISSUE THREAD

**Issue by Sypx** [jpenilla/squaremap#53]
Warning notice made by squaremap basically spammed each second, consistently telling the console about it not being able to write, this might be solved by starting the server as administrator but currently we do not want to do that while the server is up with player on. I don't get why it would want to change the settings file, afterall it is a settings file. All help is appreacieated. Sorry if I didn't follow any format, just wanted to get this out here!
[17:52:57 WARN]: [squaremap] Failed to write file 'plugins\squaremap\web\tiles\settings.json'
java.nio.file.AccessDeniedException: plugins\squaremap\web\tiles\.753935793280151--1452149791-settings.json.tmp -> plugins\squaremap\web\tiles\settings.json
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
        at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:317) ~[?:?]
        at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293) ~[?:?]
        at java.nio.file.Files.move(Files.java:1432) ~[?:?]
        at xyz.jpenilla.squaremap.common.util.FileUtil.atomicMoveIfPossible(FileUtil.java:184) ~[squaremap-paper-mc1.18.2-1.1.3.jar:?]
        at xyz.jpenilla.squaremap.common.util.FileUtil.atomicMove(FileUtil.java:152) ~[squaremap-paper-mc1.18.2-1.1.3.jar:?]
        at xyz.jpenilla.squaremap.common.util.FileUtil.writeString(FileUtil.java:132) ~[squaremap-paper-mc1.18.2-1.1.3.jar:?]
        at xyz.jpenilla.squaremap.common.util.FileUtil.lambda$writeStringAsync$7(FileUtil.java:120) ~[squaremap-paper-mc1.18.2-1.1.3.jar:?]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
        Suppressed: java.nio.file.AccessDeniedException: plugins\squaremap\web\tiles\.753935793280151--1452149791-settings.json.tmp -> plugins\squaremap\web\tiles\settings.json
                at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89) ~[?:?]
                at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
                at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:317) ~[?:?]
                at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293) ~[?:?]
                at java.nio.file.Files.move(Files.java:1432) ~[?:?]
                at xyz.jpenilla.squaremap.common.util.FileUtil.atomicMoveIfPossible(FileUtil.java:184) ~[squaremap-paper-mc1.18.2-1.1.3.jar:?]
                at xyz.jpenilla.squaremap.common.util.FileUtil.atomicMove(FileUtil.java:161) ~[squaremap-paper-mc1.18.2-1.1.3.jar:?]
                at xyz.jpenilla.squaremap.common.util.FileUtil.writeString(FileUtil.java:132) ~[squaremap-paper-mc1.18.2-1.1.3.jar:?]
                at xyz.jpenilla.squaremap.common.util.FileUtil.lambda$writeStringAsync$7(FileUtil.java:120) ~[squaremap-paper-mc1.18.2-1.1.3.jar:?]
                at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
                at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
                at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
                at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
                at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
                at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
        Suppressed: java.nio.file.AccessDeniedException: plugins\squaremap\web\tiles\.753935793280151--1452149791-settings.json.tmp -> plugins\squaremap\web\tiles\settings.json
                at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89) ~[?:?]
                at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
                at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:317) ~[?:?]
                at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293) ~[?:?]
                at java.nio.file.Files.move(Files.java:1432) ~[?:?]
                at xyz.jpenilla.squaremap.common.util.FileUtil.atomicMoveIfPossible(FileUtil.java:184) ~[squaremap-paper-mc1.18.2-1.1.3.jar:?]
                at xyz.jpenilla.squaremap.common.util.FileUtil.atomicMove(FileUtil.java:161) ~[squaremap-paper-mc1.18.2-1.1.3.jar:?]
                at xyz.jpenilla.squaremap.common.util.FileUtil.writeString(FileUtil.java:132) ~[squaremap-paper-mc1.18.2-1.1.3.jar:?]
                at xyz.jpenilla.squaremap.common.util.FileUtil.lambda$writeStringAsync$7(FileUtil.java:120) ~[squaremap-paper-mc1.18.2-1.1.3.jar:?]
                at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
                at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
                at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
                at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
                at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
                at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]

**Comment by jpenilla** [comment]
squaremap needs write access to the web directory. The plugin writes the settings for the web client to read. If you need to run the server as admin to have write to the web dir, then you have wider configuration issues. You should run the server in a folder owned by the user you're running it as.

**Comment by Sypx** [comment]
The user running the server already has full access to the entire folder and all subfolders.
