### ISSUE TITLE
Map rendering in the end and nether is broken

### ISSUE THREAD

**Issue by delow1990** [jpenilla/squaremap#6]
Was trying to generate map with version squaremap-1.1.0-SNAPSHOT+72314b9.jar and Paper-1.18.1-68
Overworld generated fine while during nether and the_end map generation server flooded logs with:

```
WARN [xyz.jpenilla.squaremap.plugin.task.render.AbstractRender] mapChunkColumn failed! 
INFO java.util.concurrent.CompletionException: java.lang.ArrayIndexOutOfBoundsException
INFO at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
INFO at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
INFO at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807) ~[?:?]
INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

The result looks like this:
![image](https://user-images.githubusercontent.com/15183139/145937121-7156bb05-9074-4ffd-9368-92cb91febe04.png)

**Comment by delow1990** [comment]
Thx for rapid fix!
