### ISSUE TITLE
error, won't load

### ISSUE THREAD

**Issue by James-Tripper** [jpenilla/squaremap#61]
upon server load i get the following

[15:09:51 ERROR]: Error occurred while enabling squaremap v1.1.4 (Is it up to date?)
squaremap.libraries.com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: BukkitCommandManager$BrigadierFailureException: Could not initialize Brigadier mappings. Reason: paper brigadier initialization failure (null)
  at Commands.<init>(Commands.java:46)
  at Commands.class(Commands.java:46)
  at SquaremapCommon.<init>(SquaremapCommon.java:61)
      \_ for 7th parameter commands
  at SquaremapCommon.class(SquaremapCommon.java:61)
  while locating SquaremapCommon

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
BukkitCommandManager$BrigadierFailureException: "squaremap.libraries.cloud.commandframework.bukkit.BukkitCommandManager$BrigadierFailureException"
Commands:                                       "xyz.jpenilla.squaremap.common.command.Commands"
SquaremapCommon:                                "xyz.jpenilla.squaremap.common.SquaremapCommon"
========================
End of classname legend:
========================

	at squaremap.libraries.com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1104) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1139) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at xyz.jpenilla.squaremap.paper.SquaremapPaper.onEnable(SquaremapPaper.java:50) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:554) ~[paper-1.19.jar:git-Paper-12]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:468) ~[paper-1.19.jar:git-Paper-12]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633) ~[paper-1.19.jar:git-Paper-12]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[paper-1.19.jar:git-Paper-12]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-12]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-12]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-12]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: squaremap.libraries.cloud.commandframework.bukkit.BukkitCommandManager$BrigadierFailureException: Could not initialize Brigadier mappings. Reason: paper brigadier initialization failure (null)
	at squaremap.libraries.cloud.commandframework.paper.PaperCommandManager.registerBrigadier(PaperCommandManager.java:134) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at xyz.jpenilla.squaremap.paper.command.PaperCommands.createCommandManager(PaperCommands.java:60) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at xyz.jpenilla.squaremap.common.command.Commands.<init>(Commands.java:68) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at squaremap.libraries.com.google.inject.internal.DefaultConstructionProxyFactory$ReflectiveProxy.newInstance(DefaultConstructionProxyFactory.java:120) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1101) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	... 13 more
Caused by: java.lang.ExceptionInInitializerError
	at squaremap.libraries.cloud.commandframework.bukkit.BukkitBrigadierMapper.registerMappings(BukkitBrigadierMapper.java:80) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.cloud.commandframework.bukkit.BukkitBrigadierMapper.<init>(BukkitBrigadierMapper.java:73) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.cloud.commandframework.paper.PaperBrigadierListener.<init>(PaperBrigadierListener.java:57) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.cloud.commandframework.paper.PaperCommandManager.registerBrigadier(PaperCommandManager.java:128) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at xyz.jpenilla.squaremap.paper.command.PaperCommands.createCommandManager(PaperCommands.java:60) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at xyz.jpenilla.squaremap.common.command.Commands.<init>(Commands.java:68) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at squaremap.libraries.com.google.inject.internal.DefaultConstructionProxyFactory$ReflectiveProxy.newInstance(DefaultConstructionProxyFactory.java:120) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1101) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	... 13 more
Caused by: java.lang.IllegalArgumentException: Cound't find the NMS class 'ArgumentRegistry', or any of the following fallbacks: [net.minecraft.commands.synchronization.ArgumentRegistry]
	at squaremap.libraries.cloud.commandframework.bukkit.internal.CraftBukkitReflection.firstNonNullOrThrow(CraftBukkitReflection.java:87) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.cloud.commandframework.bukkit.internal.CraftBukkitReflection.needNMSClassOrElse(CraftBukkitReflection.java:100) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.cloud.commandframework.bukkit.internal.MinecraftArgumentTypes.<clinit>(MinecraftArgumentTypes.java:93) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.cloud.commandframework.bukkit.BukkitBrigadierMapper.registerMappings(BukkitBrigadierMapper.java:80) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.cloud.commandframework.bukkit.BukkitBrigadierMapper.<init>(BukkitBrigadierMapper.java:73) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.cloud.commandframework.paper.PaperBrigadierListener.<init>(PaperBrigadierListener.java:57) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.cloud.commandframework.paper.PaperCommandManager.registerBrigadier(PaperCommandManager.java:128) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at xyz.jpenilla.squaremap.paper.command.PaperCommands.createCommandManager(PaperCommands.java:60) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at xyz.jpenilla.squaremap.common.command.Commands.<init>(Commands.java:68) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at squaremap.libraries.com.google.inject.internal.DefaultConstructionProxyFactory$ReflectiveProxy.newInstance(DefaultConstructionProxyFactory.java:120) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	at squaremap.libraries.com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1101) ~[squaremap-paper-mc1.18.2-1.1.4.jar:?]
	... 13 more
[15:09:51 INFO]: [squaremap] Disabling squaremap v1.1.4

**Comment by James-Tripper** [comment]
running paper1.19 and vane plugin suite 1.9.0

**Comment by jpenilla** [comment]
1.1.4 is for 1.18.2
