### ISSUE TITLE
boolean net.minecraft.server.level.EntityPlayer.bY()

### ISSUE THREAD

**Issue by BaDy17** [jpenilla/squaremap#70]
11:29:10
[squaremap]: Task #42 for squaremap v1.1.6 generated an exception
Console11:29:10
java.lang.NoSuchMethodError: 'boolean net.minecraft.server.level.EntityPlayer.bY()'
at xyz.jpenilla.squaremap.common.task.UpdatePlayers.lambda$run$0(UpdatePlayers.java:67) ~[squaremap-paper-mc1.19-1.1.6.jar:?]
at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
at xyz.jpenilla.squaremap.common.task.UpdatePlayers.lambda$run$1(UpdatePlayers.java:63) ~[squaremap-paper-mc1.19-1.1.6.jar:?]
at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
at xyz.jpenilla.squaremap.common.task.UpdatePlayers.run(UpdatePlayers.java:60) ~[squaremap-paper-mc1.19-1.1.6.jar:?]
at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.1.jar:git-Purpur-1746]
at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.1.jar:git-Purpur-1746]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1518) ~[purpur-1.19.1.jar:git-Purpur-1746]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:485) ~[purpur-1.19.1.jar:git-Purpur-1746]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1442) ~[purpur-1.19.1.jar:git-Purpur-1746]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1212) ~[purpur-1.19.1.jar:git-Purpur-1746]
at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.1.jar:git-Purpur-1746]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

I have this spam in my console, where can I fix this ?

Version server : Current: git-Purpur-1746 (MC: 1.19.1)*

**Comment by amberisvibin** [comment]
i have this same issue
```
[12:22:51 WARN]: [squaremap] Task #16 for squaremap v1.1.6 generated an exception
java.lang.NoSuchMethodError: 'boolean net.minecraft.server.level.EntityPlayer.bY()'
	at xyz.jpenilla.squaremap.common.task.UpdatePlayers.lambda$run$0(UpdatePlayers.java:67) ~[squaremap-paper-mc1.19-1.1.6.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at xyz.jpenilla.squaremap.common.task.UpdatePlayers.lambda$run$1(UpdatePlayers.java:63) ~[squaremap-paper-mc1.19-1.1.6.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at xyz.jpenilla.squaremap.common.task.UpdatePlayers.run(UpdatePlayers.java:60) ~[squaremap-paper-mc1.19-1.1.6.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.1.jar:git-Paper-109]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.1.jar:git-Paper-109]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1491) ~[paper-1.19.1.jar:git-Paper-109]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.1.jar:git-Paper-109]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1415) ~[paper-1.19.1.jar:git-Paper-109]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.1.jar:git-Paper-109]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-109]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by jpenilla** [comment]
duplicate #67
