### ISSUE TITLE
Exception running `squaremap fullrender` from console

### ISSUE THREAD

**Issue by pop4959** [jpenilla/squaremap#8]
Pretty self explanatory I think, just throws an error in console instead of handling and printing a user-friendly message.

```
squaremap
[11:24:29 INFO]: [squaremap] Invalid command syntax. Correct command syntax is: /squaremap cancelrender|confirm|fullrender|help|hide|pauserender|progresslogging|radiusrender|reload|resetmap|show
squaremap fullrender
[11:24:36 WARN]: java.util.concurrent.ExecutionException: xyz.jpenilla.squaremap.plugin.command.exception.ConsoleMustProvideWorldException
[11:24:36 WARN]:        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
[11:24:36 WARN]:        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[11:24:36 WARN]:        at squaremap-1.1.0-SNAPSHOT+1556923.jar//squaremap.libraries.cloud.commandframework.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:120)
[11:24:36 WARN]:        at squaremap-1.1.0-SNAPSHOT+1556923.jar//squaremap.libraries.cloud.commandframework.CommandManager.executeCommand(CommandManager.java:177)
[11:24:36 WARN]:        at squaremap-1.1.0-SNAPSHOT+1556923.jar//squaremap.libraries.cloud.commandframework.bukkit.BukkitCommand.execute(BukkitCommand.java:110)
[11:24:36 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[11:24:36 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:876)
[11:24:36 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchServerCommand(CraftServer.java:839)
[11:24:36 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.bf(DedicatedServer.java:507)
[11:24:36 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:481)
[11:24:36 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1470)
[11:24:36 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1264)
[11:24:36 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[11:24:36 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[11:24:36 WARN]: Caused by: xyz.jpenilla.squaremap.plugin.command.exception.ConsoleMustProvideWorldException
[11:24:36 WARN]:        at squaremap-1.1.0-SNAPSHOT+1556923.jar//xyz.jpenilla.squaremap.plugin.util.CommandUtil.resolveWorld(CommandUtil.java:40)
[11:24:36 WARN]:        at squaremap-1.1.0-SNAPSHOT+1556923.jar//xyz.jpenilla.squaremap.plugin.command.commands.FullRenderCommand.executeFullRender(FullRenderCommand.java:37)
[11:24:36 WARN]:        at squaremap-1.1.0-SNAPSHOT+1556923.jar//squaremap.libraries.cloud.commandframework.execution.CommandExecutionHandler.executeFuture(CommandExecutionHandler.java:58)
[11:24:36 WARN]:        ... 12 more
[11:24:36 INFO]: [squaremap] An internal error occurred while attempting to perform this command.
squaremap fullrender world
[11:24:51 INFO]: [squaremap] Started full map render for world
```

**Comment by jpenilla** [comment]
https://github.com/Incendo/cloud/pull/326
