### ISSUE TITLE
Server crash Quilt 1.19.2

### ISSUE THREAD

**Issue by Mylloon** [jpenilla/squaremap#83]
Hello, the server crash with the latest version of Quilt

- I am using the latest recompiled build from releases

```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'squaremap'!
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:63) ~[quilt-loader-0.18.1-beta.12.jar:?]
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[quilt-loader-0.18.1-beta.12.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:61) ~[quilt-loader-0.18.1-beta.12.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:46) ~[quilt-loader-0.18.1-beta.12.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:33) ~[quilt-loader-0.18.1-beta.12.jar:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[quilt-loader-0.18.1-beta.12.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:471) [quilt-loader-0.18.1-beta.12.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76) [quilt-loader-0.18.1-beta.12.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:31) [quilt-loader-0.18.1-beta.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.quiltmc.loader.impl.launch.server.QuiltServerLauncher.main(QuiltServerLauncher.java:63) [quilt-loader-0.18.1-beta.12.jar:?]

Caused by: java.lang.IllegalStateException: can't find /locale/ on the classpath
	at xyz.jpenilla.squaremap.common.util.FileUtil.extract(FileUtil.java:72) ~[squaremap-fabric-mc1.19.2-1.1.9-SNAPSHOTe340fd9.jar.i1.i0:0/:?]
	at xyz.jpenilla.squaremap.common.util.FileUtil.extract(FileUtil.java:63) ~[squaremap-fabric-mc1.19.2-1.1.9-SNAPSHOTe340fd9.jar.i1.i0:0/:?]
	at xyz.jpenilla.squaremap.common.config.Messages.reload(Messages.java:272) ~[squaremap-fabric-mc1.19.2-1.1.9-SNAPSHOTe340fd9.jar.i1.i0:0/:?]
	at xyz.jpenilla.squaremap.common.config.ConfigManager.reload(ConfigManager.java:45) ~[squaremap-fabric-mc1.19.2-1.1.9-SNAPSHOTe340fd9.jar.i1.i0:0/:?]
	at xyz.jpenilla.squaremap.common.config.ConfigManager.init(ConfigManager.java:35) ~[squaremap-fabric-mc1.19.2-1.1.9-SNAPSHOTe340fd9.jar.i1.i0:0/:?]
	at xyz.jpenilla.squaremap.common.SquaremapCommon.init(SquaremapCommon.java:61) ~[squaremap-fabric-mc1.19.2-1.1.9-SNAPSHOTe340fd9.jar.i1.i0:0/:?]
	at xyz.jpenilla.squaremap.fabric.SquaremapFabric.<init>(SquaremapFabric.java:48) ~[squaremap-fabric-mc1.19.2-1.1.9-SNAPSHOTe340fd9.jar.i1.i0:0/:?]
	at xyz.jpenilla.squaremap.fabric.SquaremapFabric$Initializer.onInitialize(SquaremapFabric.java:134) ~[squaremap-fabric-mc1.19.2-1.1.9-SNAPSHOTe340fd9.jar.i1.i0:0/:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startServer$2(Hooks.java:62) ~[quilt-loader-0.18.1-beta.12.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:33) ~[quilt-loader-0.18.1-beta.12.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:59) ~[quilt-loader-0.18.1-beta.12.jar:?]
	... 16 more
```

**Comment by jpenilla** [comment]
This is a quilt issue, quilt loader 0.17.6 loads squaremap fine, as does latest fabric loader, but the latest 0.18.1 quilt beta has this problem. I may rework that file extraction utility in the future which might or might not fix this indirectly, but really this seems like something that should be fixed by the loader.
